### ISSUE TITLE
Syntax field repeater in a layout breaks when switching to a different layout

### ISSUE THREAD

**Issue by MattPurland** [rainlab/pages-plugin#254]
When *changing* to a layout which has a syntax field repeater, attempting to add an item to the repeater doesn't work. This breaks all repeaters on layouts which aren't part of the layout that initially loads when creating a new page.

In a layout I have the following:

```
{repeater tab="Team" name="team_fillers" prompt="Add another team filler"}
    {mediafinder name="image" label="Image"}{/mediafinder}
{/repeater}
```

When attempting to add a new item to any repeater that isn't part of the initial layout the following error occurs:

```
A widget with class name 'formPaged41d8cd98f00b204e9800998ecf8427e590217e362185ViewBagWork' has not been bound to the controller" on line 517 of /<path>/modules/backend/Classes/Controller.php
````

Only repeaters in the original layout (the first in the dropdown list) will work, even after changing and switching back.

**Comment by MattPurland** [comment]
Will this get looked at at any point? Without the ability to use repeaters in multiple templates I'll be unable to continue :(

**Comment by LukeTowers** [comment]
@MattPurland The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that fixes this bug and wait for it to be reviewed
- [Post a bug bounty](https://www.bountysource.com/teams/october) for this specific issue so that more people can become involved with creating a fix
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

As a starter if you would like to look into it yourself, this is happening because the Repeater FormWidget from the new layout is not being bound to the RainLab.Pages Index controller when the layout is switched, only the original layout's widgets are being bound. I imagine to fix this you'll have to look into how it determines the widgets that need to be bound to the controller, and then figure out a fix that will look to the new layout when binding the widgets, not just the initial layout that was set on first page load. Keep in mind the lifecycle of requests, widgets need to be bound before the AJAX request is fully handled. AJAX requests are in and of themselves "first page load" requests to the controller as a whole, so you need to make sure that the widgets are being properly bound on the first page load and on every request in the session made afterwards to that controller. This should already be handled by the controller, it's just that it's not looking at the right layout when it does the binding of widgets on AJAX requests.

Let me know if you have any questions on how this is setup, I'd be more than happy to help you figure out the problem and solution, I just don't have spare time myself to dig into this personally. If you don't want to try to fix it yourself, then sponsoring a fix is also an option.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by RedMarlin** [comment]
I have the same problem. This is what I have discovered so far:
1.If I have only one layout for static pages, no problem I can add repeater fields and everything works as expected
2. If I have a page with already selected layout (a saved static page) that have repeater variable I can add repeater fields without problems
3. If I have a lot of layouts and any layout with repeater field is on the top of the layout dropdown list (in the page edit screen) then everything works fine
4. BUT if I have on the TOP dropdown list a layout that doesnt have a repeater, try to create a page selecting a layout with repeater and try to add fields,  then I get the error msg. To get around In this case I can select layout with repeater for this page (without adding any repeater fields) I save the page and then I reopen this page edit screen. Now I can add repeater fields without errors.

So there are three workarounds (I can think of) for this:
1. Edit page, change layout to repeater, save page, open it again and add repeater fields now.
2. Edit layout for the static page in the file (which almost the same as no.1 )
3. Have always a layout with repeater on the of the dropdown list

**Comment by Rike-cz** [comment]
The same issue: https://github.com/octobercms/october/issues/4158

**Comment by bennothommo** [comment]
@MattPurland @RedMarlin @Rike-cz There has been extensive work done on the repeater widget in the core October CMS recently. Would you be able to confirm if this issue still exists with October build 452? You will need to enable `edgeUpdates` in your config to get this version.

**Comment by LukeTowers** [comment]
Actually this may have been fixed by https://github.com/rainlab/pages-plugin/commit/eee885c0c7c136665af40b6e68e3f59f749eea5f

**Comment by bennothommo** [comment]
@LukeTowers awesome!

All, feel free to re-open this issue report if the problem still exists when using October build 452 or above.

**Comment by iboved** [comment]
The error still exists.
I have OctoberCMS Build **458** and RainLab.Pages plugin version **1.3.2**.

**Comment by bennothommo** [comment]
@iboved Can you try build 461 which was just released as an edge update? It includes some fixes for the repeater widget being used in pages. If this is to fix a live site, I would recommend trying this on a copy first.
